### ISSUE TITLE
Incorrect social media icon colour

### ISSUE THREAD

**Issue by fionamorrison23** [civictheme/uikit#245]
### Summary

The first icon in the set is the wrong colour.
![Screenshot 2024-06-17 at 12 30 29 pm](https://github.com/civictheme/uikit/assets/125337363/34cac18f-9360-4614-b04b-af9924ac8110)
![Screenshot 2024-06-17 at 12 30 18 pm](https://github.com/civictheme/uikit/assets/125337363/303bb6c6-05f0-433f-a1f5-bab8845abc29)

### Steps to reproduce

1. Go to: https://civictheme-uikit.netlify.app/?path=/story/molecules-social-links--social-links
2. Inspect the colour of the first icon (megaphone) in light theme and dark theme

### Observed outcome

The icon colour is incorrect. It appears to be #000000

### Expected outcome

It should use the 'Interaction background' colour for light and dark palettes.

**Comment by AlexSkrypnyk** [comment]
This icon is an SVG file. The component demonstrates how the *customary added SVG file* will look like. The file owner needs to provide the correct file colour. We cannot re-colour the files.

Maybe we should put a colourful icon to demonstrate this so it is not confusing that it is not broken.

**Comment by AlexSkrypnyk** [comment]
I've updated the example in the Storybook to use the image rather than icon for this item to demonstrate that this is an image-based icon.

<img width="420" alt="Molecules___Social_Links_-_Social_Links_⋅_Storybook" src="https://github.com/civictheme/uikit/assets/378794/38e6de24-21c9-430c-bc6b-fe8815f65fd5">
