### ISSUE TITLE
`With ellipsis` not working in `Pagination`.

### ISSUE THREAD

**Issue by sonamchaturvedi28** [civictheme/uikit#280]
### Summary

1. `Active is link` and `Ellipsis` attributes are not working
2. Pagination number is missing on mobile

https://github.com/civictheme/uikit/assets/51696317/9e5d1689-a005-4688-8e1d-ec8bae418282

### Steps to reproduce

1. Goto `Pagination` component
2. Observe `Active is a link` checkbox is checked
3. Verify current page link is highlighted
4. Check `With ellipsis` checkbox
5. Verify ellipsis appears
6. Switch to mobile view
7. Verify current page number renders

### Observed outcome

1. When `Active is a link` checkbox is checked then current page link is not highlighted
2. When `With ellipsis` checkbox is checked then ellipsis does not render
3. Current Page number is missing on mobile

### Expected outcome

1. When `Active is a link` checkbox is checked then current page link should be highlighted
2. When `With ellipsis` checkbox is checked then ellipsis should render
3. Current Page number should be displayed on mobile

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: FAIL
Test Result:
1. Current page link is highlighted.
2. When With ellipsis checkbox is checked then ellipsis renders, however stye on desktop is incorrect. It is same as mobile.
3. Current Page number is displayed on mobile.

Issue#2:
<img width="1228" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/ab3bfeba-2928-4f58-a494-834589ce17e6">

**Comment by AlexSkrypnyk** [comment]
The behaviour to have `... 5 ...`  instead of `1 2 ... 5 ... 10` is a correct behaviour: the current page is in the middle and it is not possible to know the first and the last page for this kind of a pager by definition (in Drupal it is called a "mini" pager and it is deliberately used for increased performance to not query for the total number of page) . Figma incorrectly shows this behaviour.
